[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0 
build_flags =
	-DRADIOLIB_BUILD_RPI_PICO
lib_deps =
	file://./RadioLib
lib_ldf_mode = deep+
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200 
